name: Lighthouse CI
# This job should only run when the `gh-pages` branch changes
# As the commit to deploy the website is executed by another workflow
# with the default GITHUB_TOKEN, Github Actions automatically prevents
# this job from being executed when specifying a simple `on: push` trigger
on:
  workflow_run:
    workflows: ["Deploy to Github Pages"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://ent8r.github.io/NotesReview/
          configPath: '.github/lighthouse/lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
